### ISSUE TITLE
op-node VPS Running Error

### ISSUE THREAD

**Issue by jessmac19** [bnb-chain/opbnb#102]
#### System information

Network: `mainnet`/`testnet`/`local`

if you are running a local node, please provide the following information:
op-node version: `op-node version`
op-geth version: `op-node -v`
OS & Version: Windows/Linux/OSX

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by STdevK** [comment]
Please describe the issue

**Comment by CocoStarZ** [comment]
Not valid issue, close it for now.
