### ISSUE TITLE
Geth rejecting all incoming and node can't connect to op-geth:8551

### ISSUE THREAD

**Issue by SeWizarD** [bnb-chain/opbnb#126]
#### System information

Network: `mainnet`/`testnet`/`local`

if you are running a local node, please provide the following information:
op-node version: `v0.2.2`
op-geth version: `v0.2.4`
OS & Version: Debian 11

Hardware:

32GB RAM
2x480GB SSD
I7-6700

#### Expected behaviour

Node Syncing and running

geth running

#### Actual behaviour

Node crashing due to connection refused

geth running but rejecting all the txs

#### Steps to reproduce the behaviour

git clone https://github.com/bnb-chain/opbnb-node-docker.git
cd opbnb-node-docker

cp .env.mainnet.example .env

Fill in all the REQUIRED parts in the .env file.

docker compose up -d

####  Logs

[log2.txt](https://github.com/bnb-chain/opbnb/files/14387262/log2.txt)
[log1.txt](https://github.com/bnb-chain/opbnb/files/14387263/log1.txt)

**Comment by SeWizarD** [comment]
I adjusted the enr like in https://github.com/bnb-chain/opbnb/issues/122 suggested

I still get many of these
![imagen](https://github.com/bnb-chain/opbnb/assets/43302794/9eae15f8-ff81-4516-b14c-0494a4e1234d)

as well as only one peer in the p2p network

![imagen](https://github.com/bnb-chain/opbnb/assets/43302794/b3e94a23-8f82-4346-982a-6f75d980f5a1)

**Comment by welkin22** [comment]
> I adjusted the enr like in #122 suggested
> 
> I still get many of these ![imagen](https://private-user-images.githubusercontent.com/43302794/307637023-9eae15f8-ff81-4516-b14c-0494a4e1234d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MTkxMTUsIm5iZiI6MTcwODkxODgxNSwicGF0aCI6Ii80MzMwMjc5NC8zMDc2MzcwMjMtOWVhZTE1ZjgtZmY4MS00NTE2LWIxNGMtMDQ5NGE0ZTEyMzRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDAzNDAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzOTRlZGQxNjViMzc4Njc3Zjg2YTlkNzkzNTlmMTVmNzJmNDMyN2U2YjgzM2RjMWM3MGJkYzMxZDNjNmYxMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xKCoRt0moFgKL5_2ifZJuEt1vPQI_eih1yYGC1_4OfI)
> 
> as well as only one peer in the p2p network
> 
> ![imagen](https://private-user-images.githubusercontent.com/43302794/307637273-b3e94a23-8f82-4346-982a-6f75d980f5a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MTkxMTUsIm5iZiI6MTcwODkxODgxNSwicGF0aCI6Ii80MzMwMjc5NC8zMDc2MzcyNzMtYjNlOTRhMjMtOGY4Mi00MzQ2LTk4MmEtNmY3NWQ5ODBmNWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDAzNDAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NWExNDc1Nzc0ODI2NGIxYWFhNTQwYzYzYWNjMGZjM2E4N2IwODg2ZThiOWQ0N2JjMjBkNDdjNDY4MjQzODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L8uW9bPqm8CWjohtSpIL_AR9rAkyZxfuoidrdK1-THM)

@SeWizarD Hi, based on your first log, I guess there is a problem with the L1 endpoint you configured, which caused the op-node to fail to retrieve data from the L1 network. You can check if the L1 endpoint you configured for op-node is functioning properly.

**Comment by SeWizarD** [comment]
still having issues syncing 
tried on a fresh setup

![imagen](https://github.com/bnb-chain/opbnb/assets/43302794/e187f351-e66b-40bb-8015-9e72f5d8e403)

I got 28 peers

I used different nodes, official ones and premium paid rpcs for the L1

Node doesn't seem to sync
`
op-node-1  | t=2024-03-02T01:51:35+0000 lvl=dbug msg="validated block"                        result=ACCEPT from=16Uiu2HAkvzACkRnRigZxosm6Aq3XmPK9RnuAEXJ3C3t2Rat8oxjc
op-node-1  | t=2024-03-02T01:51:35+0000 lvl=info msg="Received signed execution payload from p2p" id=0x977990a71bfffb5ab0ff288104de47dc14de822c4de8674f153effb54e7600f6:17590572 peer=16Uiu2HAkvzACkRnRigZxosm6Aq3XmPK9RnuAEXJ3C3t2Rat8oxjc
op-node-1  | t=2024-03-02T01:51:35+0000 lvl=info msg="Optimistically queueing unsafe L2 execution payload" id=0x977990a71bfffb5ab0ff288104de47dc14de822c4de8674f153effb54e7600f6:17590572
op-node-1  | t=2024-03-02T01:51:35+0000 lvl=dbug msg="Derivation process step"                onto_origin=0x29443b21507894febe7700f7c5cd3569cc8bf1ba535df0489276d8004af81044:30758357 attempts=0
op-geth-1  | WARN [03-02|01:51:35.158] Peer's transaction rejected              peer=3526b4377a436f2db214adaa974b497d54797d0a040f4e3fa5b0774b9ff57207 txHash=0xe4b17ca587377c68dc8dd51e34128acddde5aff6c5c98543830f3660dd0ceea0 err="insufficient funds for gas * price + value"
op-geth-1  | WARN [03-02|01:51:35.161] Peer's transaction rejected              peer=2f1dcad170b9e4acf3bcb700379fb3d368b9f57d25630aadc5ab3f95be80212f txHash=0x08b92b889173810cb9eb18c7ba9a70866752e7ab5a875566e5c34a20f1c2ada4 err="insufficient funds for gas * price + value"
op-geth-1  | INFO [03-02|01:51:35.164] Forkchoice requested sync to new head    number=17,590,572 hash=977990..7600f6 finalized=unknown                      op-node-1  | t=2024-03-02T01:51:35+0000 lvl=info msg="Sync progress"                          reason="unsafe payload from sequencer" l2_finalized=0x4dd61178c
8b0f01670c231597e7bcb368e84545acd46d940a896d6a791dd6df4:0 l2_safe=0x4dd61178c8b0f01670c231597e7bcb368e84545acd46d940a896d6a791dd6df4:0 l2_unsafe=0x4dd61178c8b0f01670c231597e7bcb368e84545acd46d940a896d6a791dd6df4:0 l2_engineSyncTarget=0x977990a71bfffb5ab0ff288104de47dc14de822c4de8674f153effb54e7600f6:17590572 l2_t
ime=1,691,753,723 l1_derived=0x29443b21507894febe7700f7c5cd3569cc8bf1ba535df0489276d8004af81044:30758357                                                     op-node-1  | t=2024-03-02T01:51:35+0000 lvl=dbug msg="Derivation process step"                onto_origin=0x29443b21507894febe7700f7c5cd3569cc8bf1ba535df0489
276d8004af81044:30758357 attempts=0                                                                                                                          op-node-1  | t=2024-03-02T01:51:35+0000 lvl=dbug msg="Derivation process went idle because the engine is syncing" progress=0x29443b21507894febe7700f7c5cd3569
cc8bf1ba535df0489276d8004af81044:30758357 sync_target=0x977990a71bfffb5ab0ff288104de47dc14de822c4de8674f153effb54e7600f6:17590572 err="engine is P2P syncing"
op-node-1  | t=2024-03-02T01:51:36+0000 lvl=dbug msg="validated block"                        result=ACCEPT from=16Uiu2HAm2UZnecwWkKRKZ4iLSmFPGbSg4LY3rWtzBDfJjB3iTKC2
op-node-1  | t=2024-03-02T01:51:36+0000 lvl=info msg="Received signed execution payload from p2p" id=0x05d13df85f64053c9ca04e3021e745e4916143fa0185b93087db5a1bd8b725c0:17590573 peer=16Uiu2HAm2UZnecwWkKRKZ4iLSmFPGbSg4LY3rWtzBDfJjB3iTKC2
op-node-1  | t=2024-03-02T01:51:36+0000 lvl=info msg="Optimistically queueing unsafe L2 execution payload" id=0x05d13df85f64053c9ca04e3021e745e4916143fa0185b93087db5a1bd8b725c0:17590573
op-node-1  | t=2024-03-02T01:51:36+0000 lvl=dbug msg="Derivation process step"                onto_origin=0x29443b21507894febe7700f7c5cd3569cc8bf1ba535df0489276d8004af81044:30758357 attempts=0
op-geth-1  | INFO [03-02|01:51:36.166] Forkchoice requested sync to new head    number=17,590,573 hash=05d13d..b725c0 finalized=unknown                      op-node-1  | t=2024-03-02T01:51:36+0000 lvl=info msg="Sync progress"                          reason="unsafe payload from sequencer" l2_finalized=0x4dd61178c
8b0f01670c231597e7bcb368e84545acd46d940a896d6a791dd6df4:0 l2_safe=0x4dd61178c8b0f01670c231597e7bcb368e84545acd46d940a896d6a791dd6df4:0 l2_unsafe=0x4dd61178c8b0f01670c231597e7bcb368e84545acd46d940a896d6a791dd6df4:0 l2_engineSyncTarget=0x05d13df85f64053c9ca04e3021e745e4916143fa0185b93087db5a1bd8b725c0:17590573 l2_t
ime=1,691,753,723 l1_derived=0x29443b21507894febe7700f7c5cd3569cc8bf1ba535df0489276d8004af81044:30758357                                                     op-node-1  | t=2024-03-02T01:51:36+0000 lvl=dbug msg="Derivation process step"                onto_origin=0x29443b21507894febe7700f7c5cd3569cc8bf1ba535df0489
276d8004af81044:30758357 attempts=0                                                                                                                          op-node-1  | t=2024-03-02T01:51:36+0000 lvl=dbug msg="Derivation process went idle because the engine is syncing" progress=0x29443b21507894febe7700f7c5cd3569
cc8bf1ba535df0489276d8004af81044:30758357 sync_target=0x05d13df85f64053c9ca04e3021e745e4916143fa0185b93087db5a1bd8b725c0:17590573 err="engine is P2P syncing"op-node-1  | t=2024-03-02T01:51:36+0000 lvl=dbug msg="Revalidated node"                       p2p=discv5 b=15 id=50826867d4cf2d0f5d43485e0d40209b0c084e1def66
61026da9eb24f09a2df4 checks=5  `
`op-node-1  | t=2024-03-02T01:51:36+0000 lvl=dbug msg="requesting sync with open-end range"    start=0x4dd61178c8b0f01670c231597e7bcb368e84545acd46d940a896d6a791dd6df4:0
op-node-1  | t=2024-03-02T01:51:36+0000 lvl=dbug msg="ignoring request to sync L2 range, timestamp is too old for p2p" start=0x4dd61178c8b0f01670c231597e7bcb368e84545acd46d940a896d6a791dd6df4:0 end=0x0000000000000000000000000000000000000000000000000000000000000000:0 start_time=1,691,753,723
op-node-1  | t=2024-03-02T01:51:36+0000 lvl=dbug msg="failed to fetch block ref"              err="failed to fetch header by num 30758360: not found" blockNumber=30,758,360
`

Last time it synced over a week up to 9M which is about half the size and already took ~380GB 

Any quick way to get the node to have just a cut state of the chain and not sync everything?

**Comment by welkin22** [comment]
> @welkin22 still having issues syncing tried on a fresh setup
> 
> ![imagen](https://private-user-images.githubusercontent.com/43302794/309431409-e187f351-e66b-40bb-8015-9e72f5d8e403.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MTg5NTcsIm5iZiI6MTcwOTUxODY1NywicGF0aCI6Ii80MzMwMjc5NC8zMDk0MzE0MDktZTE4N2YzNTEtZTY2Yi00MGJiLTgwMTUtOWU3MmY1ZDhlNDAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDAyMTczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxNjM4Y2MzMzA2NjMzMWIxODk1YjY2ZWU2NDJlYmUwNGQzY2M5ZmYxNzY5ZjQzYTliZTU2NDVjZTI4MzFiYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9mm9jCIq7JfvE3VyUd06v1FzkCoYgyBqNgxVKRp8e1o)
> 
> I got 28 peers
> 
> I used different nodes, official ones and premium paid rpcs for the L1
> 
> Node doesn't seem to sync
> 
> ```
> op-node-1  | t=2024-03-02T01:51:35+0000 lvl=dbug msg="validated block" result=ACCEPT from=16Uiu2HAkvzACkRnRigZxosm6Aq3XmPK9RnuAEXJ3C3t2Rat8oxjc
> op-node-1  | t=2024-03-02T01:51:35+0000 lvl=info msg="Received signed execution payload from p2p" id=0x977990a71bfffb5ab0ff288104de47dc14de822c4de8674f153effb54e7600f6:17590572 peer=16Uiu2HAkvzACkRnRigZxosm6Aq3XmPK9RnuAEXJ3C3t2Rat8oxjc
> op-node-1  | t=2024-03-02T01:51:35+0000 lvl=info msg="Optimistically queueing unsafe L2 execution payload" id=0x977990a71bfffb5ab0ff288104de47dc14de822c4de8674f153effb54e7600f6:17590572
> op-node-1  | t=2024-03-02T01:51:35+0000 lvl=dbug msg="Derivation process step" onto_origin=0x29443b21507894febe7700f7c5cd3569cc8bf1ba535df0489276d8004af81044:30758357 attempts=0
> op-geth-1  | WARN [03-02|01:51:35.158] Peer's transaction rejected peer=3526b4377a436f2db214adaa974b497d54797d0a040f4e3fa5b0774b9ff57207 txHash=0xe4b17ca587377c68dc8dd51e34128acddde5aff6c5c98543830f3660dd0ceea0 err="insufficient funds for gas * price + value"
> op-geth-1  | WARN [03-02|01:51:35.161] Peer's transaction rejected peer=2f1dcad170b9e4acf3bcb700379fb3d368b9f57d25630aadc5ab3f95be80212f txHash=0x08b92b889173810cb9eb18c7ba9a70866752e7ab5a875566e5c34a20f1c2ada4 err="insufficient funds for gas * price + value"
> op-geth-1  | INFO [03-02|01:51:35.164] Forkchoice requested sync to new head number=17,590,572 hash=977990..7600f6 finalized=unknown
> op-node-1  | t=2024-03-02T01:51:35+0000 lvl=info msg="Sync progress" reason="unsafe payload from sequencer" l2_finalized=0x4dd61178c8b0f01670c231597e7bcb368e84545acd46d940a896d6a791dd6df4:0 l2_safe=0x4dd61178c8b0f01670c231597e7bcb368e84545acd46d940a896d6a791dd6df4:0 l2_unsafe=0x4dd61178c8b0f01670c231597e7bcb368e84545acd46d940a896d6a791dd6df4:0 l2_engineSyncTarget=0x977990a71bfffb5ab0ff288104de47dc14de822c4de8674f153effb54e7600f6:17590572 l2_time=1,691,753,723 l1_derived=0x29443b21507894febe7700f7c5cd3569cc8bf1ba535df0489276d8004af81044:30758357
> op-node-1  | t=2024-03-02T01:51:35+0000 lvl=dbug msg="Derivation process step" onto_origin=0x29443b21507894febe7700f7c5cd3569cc8bf1ba535df0489276d8004af81044:30758357 attempts=0
> op-node-1  | t=2024-03-02T01:51:35+0000 lvl=dbug msg="Derivation process went idle because the engine is syncing" progress=0x29443b21507894febe7700f7c5cd3569cc8bf1ba535df0489276d8004af81044:30758357 sync_target=0x977990a71bfffb5ab0ff288104de47dc14de822c4de8674f153effb54e7600f6:17590572 err="engine is P2P syncing"
> op-node-1  | t=2024-03-02T01:51:36+0000 lvl=dbug msg="validated block" result=ACCEPT from=16Uiu2HAm2UZnecwWkKRKZ4iLSmFPGbSg4LY3rWtzBDfJjB3iTKC2
> op-node-1  | t=2024-03-02T01:51:36+0000 lvl=info msg="Received signed execution payload from p2p" id=0x05d13df85f64053c9ca04e3021e745e4916143fa0185b93087db5a1bd8b725c0:17590573 peer=16Uiu2HAm2UZnecwWkKRKZ4iLSmFPGbSg4LY3rWtzBDfJjB3iTKC2
> op-node-1  | t=2024-03-02T01:51:36+0000 lvl=info msg="Optimistically queueing unsafe L2 execution payload" id=0x05d13df85f64053c9ca04e3021e745e4916143fa0185b93087db5a1bd8b725c0:17590573
> op-node-1  | t=2024-03-02T01:51:36+0000 lvl=dbug msg="Derivation process step" onto_origin=0x29443b21507894febe7700f7c5cd3569cc8bf1ba535df0489276d8004af81044:30758357 attempts=0
> op-geth-1  | INFO [03-02|01:51:36.166] Forkchoice requested sync to new head number=17,590,573 hash=05d13d..b725c0 finalized=unknown
> op-node-1  | t=2024-03-02T01:51:36+0000 lvl=info msg="Sync progress" reason="unsafe payload from sequencer" l2_finalized=0x4dd61178c8b0f01670c231597e7bcb368e84545acd46d940a896d6a791dd6df4:0 l2_safe=0x4dd61178c8b0f01670c231597e7bcb368e84545acd46d940a896d6a791dd6df4:0 l2_unsafe=0x4dd61178c8b0f01670c231597e7bcb368e84545acd46d940a896d6a791dd6df4:0 l2_engineSyncTarget=0x05d13df85f64053c9ca04e3021e745e4916143fa0185b93087db5a1bd8b725c0:17590573 l2_time=1,691,753,723 l1_derived=0x29443b21507894febe7700f7c5cd3569cc8bf1ba535df0489276d8004af81044:30758357
> op-node-1  | t=2024-03-02T01:51:36+0000 lvl=dbug msg="Derivation process step" onto_origin=0x29443b21507894febe7700f7c5cd3569cc8bf1ba535df0489276d8004af81044:30758357 attempts=0
> op-node-1  | t=2024-03-02T01:51:36+0000 lvl=dbug msg="Derivation process went idle because the engine is syncing" progress=0x29443b21507894febe7700f7c5cd3569cc8bf1ba535df0489276d8004af81044:30758357 sync_target=0x05d13df85f64053c9ca04e3021e745e4916143fa0185b93087db5a1bd8b725c0:17590573 err="engine is P2P syncing"
> op-node-1  | t=2024-03-02T01:51:36+0000 lvl=dbug msg="Revalidated node" p2p=discv5 b=15 id=50826867d4cf2d0f5d43485e0d40209b0c084e1def6661026da9eb24f09a2df4 checks=5
> op-node-1  | t=2024-03-02T01:51:36+0000 lvl=dbug msg="requesting sync with open-end range" start=0x4dd61178c8b0f01670c231597e7bcb368e84545acd46d940a896d6a791dd6df4:0
> op-node-1  | t=2024-03-02T01:51:36+0000 lvl=dbug msg="ignoring request to sync L2 range, timestamp is too old for p2p" start=0x4dd61178c8b0f01670c231597e7bcb368e84545acd46d940a896d6a791dd6df4:0 end=0x0000000000000000000000000000000000000000000000000000000000000000:0 start_time=1,691,753,723
> op-node-1  | t=2024-03-02T01:51:36+0000 lvl=dbug msg="failed to fetch block ref" err="failed to fetch header by num 30758360: not found" blockNumber=30,758,360
> ```
> 
> Last time it synced over a week up to 9M which is about half the size and already took ~380GB
> 
> This time it seems to slowly fill up the disk but the method to get the blocknr returns 0
> 
> Any quick way to get the node to have just a cut state of the chain and not sync everything?

@SeWizarD I saw the phrase `engine is P2P syncing` in your log, which means that engine sync is working. In the first stage of engine sync, the block height will not increase, so maybe if you wait longer, you will see that the sync is working normally. If you can send out the op-geth log, we can help you confirm whether the sync is working normally. It is best to enable debug logs by modifying the startup parameter `verbosity=4`.

>Any quick way to get the node to have just a cut state of the chain and not sync everything?

You can try changing the parameter `--syncmode=full` to `--syncmode=snap`, snapsync mode will only synchronize the state tree of the latest block, instead of all states starting from the genesis block.
