### ISSUE TITLE
Upon listing an NFT and entering listing price, if there's a comma instead of a dot in the price, there is an error. We can easily fix it

### ISSUE THREAD

**Issue by tartsmart** [bnb-chain/opbnb#128]
#### System information

Network: `mainnet`

#### Expected behaviour
Both comma and dot are interpreted the as the same input data (comma "," should be read or autocorrected into a dot ".")

#### Actual behaviour
There is an error message whenever there is a comma "," in the listing price. Thus listing cannot be executed.

#### Steps to reproduce the behaviour
Mint a PFP or image -> In the listing process type 0,01 -> Press "List".

````
Error message: Cannot convert NaN000000000000000000 to a BigInt

**Comment by welkin22** [comment]
> #### System information
> Network: `mainnet`
> 
> #### Expected behaviour
> Both comma and dot are interpreted the as the same input data (comma "," should be read or autocorrected into a dot ".")
> 
> #### Actual behaviour
> There is an error message whenever there is a comma "," in the listing price. Thus listing cannot be executed.
> 
> #### Steps to reproduce the behaviour
> Mint a PFP or image -> In the listing process type 0,01 -> Press "List".
> 
> ```
> Error message: Cannot convert NaN000000000000000000 to a BigInt
> ```

@tartsmart Hi, I cannot determine the problem based on the information provided. Where are you trying to Mint a PFP or image? Are you trying this operation on a website or using a json-rpc request? If it's a website, what is the address? If it's a json-rpc request, what does your original transaction or json-rpc request look like?
