### ISSUE TITLE
Add the "Switch to opBNB network" window prompt 

### ISSUE THREAD

**Issue by tartsmart** [bnb-chain/opbnb#129]
# Rationale

1. When you try to list a minted NFT and the network in your wallet is not opBNB, there is currently an error message pop-up that reads:
"Address "undefined" is invalid.
Version: viem@1.21.3"
2. There should instead be a window prompt pop-up that lets the user to switch the network to opBNB in their wallet.
3. There should also be a "network switch" button in the website's UI, that says "WRONG NETWORK" if you're not on opBNB.

# Implementation

This is a common feature that exists on many websites across the crypto space. Whenever there is an unsupported network, the UI tells you this, and whenever you try to execute something on the wrong network, it prompts you to switch to one of the supported networks.

**Comment by welkin22** [comment]
> # Rationale
> 1. When you try to list a minted NFT and the network in your wallet is not opBNB, there is currently an error message pop-up that reads:
>    "Address "undefined" is invalid.
>    Version: viem@1.21.3"
> 2. There should instead be a window prompt pop-up that lets the user to switch the network to opBNB in their wallet.
> 3. There should also be a "network switch" button in the website's UI, that says "WRONG NETWORK" if you're not on opBNB.
> 
> # Implementation
> This is a common feature that exists on many websites across the crypto space. Whenever there is an unsupported network, the UI tells you this, and whenever you try to execute something on the wrong network, it prompts you to switch to one of the supported networks.

@tartsmart Hi, which page are you referring to? Can you please send the URL?
