### ISSUE TITLE
high cpu usage and iowait when idle

### ISSUE THREAD

**Issue by goldsquid** [bnb-chain/opbnb#173]
I'm using 2 server grade nvme in raid0 at 30% capcity running op-bnb/geth and op-bnb/node seeing 3% iowait and constant read access when runniung the archive node from the snapshot. 

comparing that with optimism rollups of the same datadir size that's concerning as other rollups using hash state scheme and leveldb as backend are basically idle on the disk. I'm running the latest release 0.3.0 from last week.

I doubt that I can just switch out op-bnb for op-geth due to tuned block gas parameters.

**Comment by goldsquid** [comment]
another issue is that after a few days of running without issues it stops progressing for me. I checked the logs. no error. went though 4 GB of logs for 3 days. blocknumber is not advancing.

**Comment by STdevK** [comment]
What's your node start-up command?

**Comment by goldsquid** [comment]
I use this docker-compose https://github.com/StakeSquid/ethereum-rpc-docker/blob/main/op-bnb.yml which is copied from the reference docker-compose with the variables filled in.

**Comment by krish-nr** [comment]
> another issue is that after a few days of running without issues it stops progressing for me. I checked the logs. no error. went though 4 GB of logs for 3 days. blocknumber is not advancing.

Could you pls check if there's keyword "**Database compacting, degraded performance**" in **geth** log?

**Comment by goldsquid** [comment]
The keywords are not in the log

**Comment by krish-nr** [comment]
@goldsquid could you paste the recent logs from both op-node and op-geth here so that we can analyze the issue?
