### ISSUE TITLE
Will opBNB submit the transaction data to BSC?

### ISSUE THREAD

**Issue by wolfbrother** [bnb-chain/opbnb#206]
Recently, while analyzing opBNB's technology, it is observed that opBNB submits the L2 state through the interface proposeL2Output(_outputRoot, _l2BlockNumber, _l1BlockHash, _l2BlockNumber) of the contract (contract address 0x0d61A015BAeF63f6740afF8294dAc278A494f6fA) on BSC.

However, it is not clear what interface opBNB uses to submit L2 block transaction data or which contract address is mentioned. If opBNB does not submit transaction data to BSC, it is not a standard Rollup.

Could you please provide the contract address on BSC that receives opBNB's L2 batch transaction data?

**Comment by welkin22** [comment]
> Recently, while analyzing opBNB's technology, it is observed that opBNB submits the L2 state through the interface proposeL2Output(_outputRoot, _l2BlockNumber, _l1BlockHash, _l2BlockNumber) of the contract (contract address 0x0d61A015BAeF63f6740afF8294dAc278A494f6fA) on BSC.
> 
> However, it is not clear what interface opBNB uses to submit L2 block transaction data or which contract address is mentioned. If opBNB does not submit transaction data to BSC, it is not a standard Rollup.
> 
> Could you please provide the contract address on BSC that receives opBNB's L2 batch transaction data?

Please refer to our documentation website: https://docs.bnbchain.org/bnb-opbnb/core-concepts/opbnb-protocol-addresses/
