### ISSUE TITLE
Transaction validation failing after 200th block

### ISSUE THREAD

**Issue by BassamMunib** [bnb-chain/opbnb#219]
#### System information

Network: `local`

if you are running a local node, please provide the following information:
op-node version: `v18.18.0`
op-geth version: `v1.4.11`
OS & Version: Linux

#### Expected behaviour

The validation should work as working before 200th block

#### Actual behaviour

The validation starts failing after 200th block

#### Steps to reproduce the behaviour

https://github.com/bnb-chain/bsc cloned this repo, setup genesis file using repos readme, and start the node using command

./bsc/build/bin/geth \
            --networkid 18923 \
            --datadir ./bsc/chainData \
            --http \
            --http.addr "0.0.0.0" \
            --http.api "eth,net,web3,personal,txpool,parlia" \
            --http.corsdomain "*" \
            --mine \
            --miner.etherbase 0x64AffDD3f181788f61A73ebe4EEC85E228BDe70B \
            --allow-insecure-unlock \

#### Backtrace

[message.txt](https://github.com/user-attachments/files/16336981/message.txt)

**Comment by OmarMBNB** [comment]
Thanks for your patience, can you try the following https://ethereum.stackexchange.com/questions/68249/block-sealing-failed-err-unauthorized-signer ?

**Comment by BassamMunib** [comment]
> Thanks for your patience, can you try the following https://ethereum.stackexchange.com/questions/68249/block-sealing-failed-err-unauthorized-signer ?

Thanks for the reply, yes i've tried it and added validator into the extra data which works fine until 200th blocks.

**Comment by redhdx** [comment]
I think your problem should not be under the opbnb repository. It seems that you have a problem starting the local bsc network rather than opbnb.
