### ISSUE TITLE
opbnb-node running warring Failed to insert unsafe payload for EL sync

### ISSUE THREAD

**Issue by orange723** [bnb-chain/opbnb#242]
INFO [09-09|07:14:05.569] Optimistically inserting unsafe L2 execution payload to drive EL sync id=9d086d..24e1bc:34112322
INFO [09-09|07:14:05.572] el sync triggered as unexpected
WARN [09-09|07:14:05.572] Failed to insert unsafe payload for EL sync id=9d086d..24e1bc:34112322 err="temp: cannot process unsafe payload: new - 0x9d086d830c5195cdd12bafc6a5abf87c1a685f19aa9a0c095d1a651be924e1bc:34112322; parent: 0x6b26a80cb4b7b5c1617a68857c7199ca899a9aa8ce0ec81aa89228de3323df6c:34112321; err: unknown execution status on 0x9d086d830c5195cdd12bafc6a5abf87c1a685f19aa9a0c095d1a651be924e1bc:34112322: \"\", "

opbnb-geth is not run

geth version 0.5.0
node version 0.5.0

**Comment by orange723** [comment]
geth command

```sh
./op-gethv0.5.0 --datadir ./op-geth-data/ --cache 8000 --networkid 204 --state.scheme path --db.engine pebble --ws --ws.addr 0.0.0.0 --ws.port 8545 --ws.origins '*' --ws.api 'eth,engine' --http --http.corsdomain '*' --http.addr 0.0.0.0 --http.port 8546 --http.vhosts '*' --http.api 'net,eth,engine' --discovery.port 30304 --port 30304 --rpc.allow-unprotected-txs --history.transactions 0 --syncmode full --verbosity 3 --maxpeers 10 --miner.gaslimit 150000000 --txpool.globalslots 10000 --txpool.globalqueue 5000 --txpool.accountqueue 200 --txpool.accountslots 200 --cache.preimages --allow-insecure-unlock --authrpc.addr 0.0.0.0 --authrpc.port 8652 --authrpc.vhosts '*' --authrpc.jwtsecret './jwt.txt' --gcmode archive --rollup.sequencerhttp 'https://opbnb-mainnet-rpc.bnbchain.org' --bootnodes 'enr:-KO4QHs5qh_kPFcjMgqkuN9dbxXT4C5Cjad4SAheaUxveCbJQ3XdeMMDHeHilHyqisyYQAByfdhzyKAdUp2SvyzWeBqGAYvRDf80g2V0aMfGhHFtSjqAgmlkgnY0gmlwhDaykUmJc2VjcDI1NmsxoQJUevTL3hJwj21IT2GC6VaNqVQEsJFPtNtO-ld5QTNCfIRzbmFwwIN0Y3CCdl-DdWRwgnZf,enr:-KO4QKIByq-YMjs6IL2YCNZEmlo3dKWNOy4B6sdqE3gjOrXeKdNbwZZGK_JzT1epqCFs3mujjg2vO1lrZLzLy4Rl7PyGAYvRA8bEg2V0aMfGhHFtSjqAgmlkgnY0gmlwhDbjSM6Jc2VjcDI1NmsxoQNQhJ5pqCPnTbK92gEc2F98y-u1OgZVAI1Msx-UiHezY4RzbmFwwIN0Y3CCdl-DdWRwgnZf' --txlookuplimit 0
```

**Comment by orange723** [comment]
I change L1 rpc fix it

**Comment by tardigralice** [comment]
which L1 did you used ?
i tested with public, not work
i tested with my own full node , not work.

**Comment by orange723** [comment]
> which L1 did you used ? i tested with public, not work i tested with my own full node , not work.

I use myself deploy bnb rpc，use docker deploy opbnb download latest snapshot，it's work and sync block

**Comment by appop** [comment]
I have the same error with you, but after I use docker start it, the l2 node have a lot of info log like:
t=2024-09-16T06:30:50+0000 lvl=info msg="Walking back L1Block by hash" curr=0x67e648b2b02dcbcbfd72651a6475b95a60408218f73b1b4cbaa9b93dc6ac45f0:41794769 next=0xa3e12b629a6443667506b75ccffec0ab641baf28e3cbf569384066f3b21c7b4e:41794768 l2block=0x98add7fb651746fcd102a5c031022f2128677d7ce845011857f6256854ecf510:33204640
t=2024-09-16T06:30:50+0000 lvl=info msg="Walking back L1Block by hash" curr=0xa3e12b629a6443667506b75ccffec0ab641baf28e3cbf569384066f3b21c7b4e:41794768 next=0x619fdb5ee008d97cb20151c47ad546708158c6d11805bf6439a6b533a73a5f60:41794767 l2block=0xb1720bedf84e96eb7208b1169845ba5a9b4a1a5bf63ecac554c577829f1a6e2b:33204637
t=2024-09-16T06:30:50+0000 lvl=info msg="Walking back L1Block by hash" curr=0x619fdb5ee008d97cb20151c47ad546708158c6d11805bf6439a6b533a73a5f60:41794767 next=0xbc68efbf5d1c3292026ea128470a43fa37bea76cdba6b0ea39c706e4b29ea46e:41794766 l2block=0x174df6367b5a6dc1682b96ed9b82c24700dbd6f533c423d91443b8442cae2d1d:33204634

but the l2 block info said:
INFO [09-16|06:26:10.985] Loaded most recent local header          number=33,233,079 hash=fab248..04e9e5 td=0 age=2w3d3h
INFO [09-16|06:26:10.985] Loaded most recent local block           number=33,228,000 hash=8a83a3..77e601 td=0 age=2w3d4h
INFO [09-16|06:26:10.985] Loaded most recent local snap block      number=33,233,079 hash=fab248..04e9e5 td=0 age=2w3d3h
INFO [09-16|06:26:10.985] Loaded most recent local finalized block number=33,232,982 hash=cfa235..eeff3c td=0 age=2w3d3h
WARN [09-16|06:26:10.987] Enabling snapshot recovery               chainhead=33,228,000 diskbase=33,228,000
