### ISSUE TITLE
How to enable auto-prove-finalize withdraw with script, like in manual

### ISSUE THREAD

**Issue by oleggrib** [bnb-chain/opbnb#251]
Hello. I an working with deposit/withdraw custom ERC20 token BSC<->opBNB using script from official manual 
https://docs.bnbchain.org/bnb-opbnb/developers/bep20-crosschain/

In this script user need to wait 2 times . and in case if user forget to back to the script and do `prove` action in 30min interval then funds will be lost completely. It unacceptable way to withdraw funds.

I can see in official bridge opBNB->BSC option to auto-prove-withdraw.

How to update optimism-sdk script to enable option to auto-prove-withdraw ?

Do we have an option to get data for "prove" after 30-min interval?

Thank you!

**Comment by owen-reorg** [comment]
Hi, the optimism-sdk cannot do this. 

We deployed a smart contract on opbnb that wraps the withdrawal logic. We also started a service to monitor withdrawal events in our wrapped contract, assisting users with the proof and finalization process.

Please note that we charge a user fee in the contract to cover the proof and finalization fee on L1.

The project is open source; you can find more details at https://github.com/bnb-chain/opbnb-bridge-bot. We have implemented a whitelist mechanism in the official version to prevent potential attacks involving malicious tokens. If you want your token to be supported in this way, you may need to run your own service.
