### ISSUE TITLE
Want to participate in mainnet.

### ISSUE THREAD

**Issue by alexqrid** [bnb-chain/opbnb#28]
Hi! We are building an ad-free [open-source](https://github.com/3xplcom/Core) explorer 3xpl.com and would like to add opbnb to our website. Can we get the mainnet genesis file? Is the latest tag (0.1.3) suitable for mainnet usage?

**Comment by deepcrazy** [comment]
Hi there, This info. is not available yet. This will be announced once it is made available and running mainnet nodes are opened to the community.
