### ISSUE TITLE
verifying contract through foundry fails 

### ISSUE THREAD

**Issue by MuesliW** [bnb-chain/opbnb#31]
example of foundry.toml

I reference this documentation (https://docs.bnbchain.org/opbnb-docs/docs/tutorials/opbnbscan-verify-hardhat-truffle) and try to verify contract through foundry:

```md
[etherscan]
opBNB = { key = "${ETHERSCAN_API_KEY}", chain=5611, url="https://open-platform.nodereal.io/${NODEREAL_KEY}/op-bnb-testnet/contract/" }
```

Message

```md
Error: 
expected value at line 1 column 1
```

The contract is pushed and deployed on the network however it is not verified on the opBNBscan

CLI:
`forge create`

**Comment by CocoStarZ** [comment]
Suggest you verify contract using hardhat as explained in doc
