### ISSUE TITLE
verify contract failed using nodereal api

### ISSUE THREAD

**Issue by likegogogo** [bnb-chain/opbnb#38]
using the method in https://docs.bnbchain.org/opbnb-docs/docs/tutorials/opbnbscan-verify-hardhat-truffle#hardhat to verify contract in opbnb testnet(chainId: 5611), but failed always.

abc...

**Comment by deepcrazy** [comment]
Hi there, It seems like the contract has been already verified: https://opbnbscan.com/address/0xAd66999c3E477f315F6fc8e8065267E1a4c72864?p=1&tab=Contract.
Is there anything else you would like to highlight here?

**Comment by okokstuff** [comment]
using the mentioned method, when contract params number is large than 0, it has problem.
when contract params number is large than 0, using this method can work:
npx hardhat verify --network opbnb-goerli contract_addr params...
but need manually verify.
