### ISSUE TITLE
I followed the tutorial to set up a local network on L2, but it failed.

### ISSUE THREAD

**Issue by TralaTomJeong** [bnb-chain/opbnb#46]
I followed the steps as follows, but it didn't work.

<pre>
<code>
101-L2CrossDomainMessengerlmpl.ts
const Artifact__L1CrossDomainMessenger = await hre.companionNetworks[
    'l1'
  ].deployments.get('L1CrossDomainMessengerProxy')

102-L2StandarBridgelmpl.ts
const Artifact__L1StandardBridge = await hre.companionNetworks[
    'l1'
  ].deployments.get('L1StandardBridgeProxy')
</code>
</pre>

It worked after making these modifications.

<pre>
<code>
const Artifact__L1CrossDomainMessenger = await hre.companionNetworks[
    'l1'
  ].deployments.get('Proxy__OVM_L1CrossDomainMessenger')

const Artifact__L1StandardBridge = await hre.companionNetworks[
    'l1'
  ].deployments.get('Proxy__OVM_L1StandardBridge')
</code>
</pre>

Is this the correct way to proceed?

**Comment by TralaTomJeong** [comment]
https://docs.bnbchain.org/opbnb-docs/docs/tutorials/running-a-local-development-environment

**Comment by huihzhao** [comment]
Thanks, @TralaTomJeong we will check this issue and revert to you

**Comment by welkin22** [comment]
@TralaTomJeong Hi, We have updated the documentation and code, and you should now be able to run a complete development environment locally. Please refer to the documentation again at https://docs.bnbchain.org/opbnb-docs/docs/tutorials/running-a-local-development-environment to give it a try. If you have any questions, please feel free to provide further feedback.

**Comment by welkin22** [comment]
This issue has been inactive for a long time, so I will close it. Please feel free to ask again if you have any questions.
