### ISSUE TITLE
There is an issue in initializing variable directly in the return type; unlike in other EVM.

### ISSUE THREAD

**Issue by chrisckwong821** [bnb-chain/opbnb#47]
Minimal Example:

Reproducible Example:
call getUserMaxBorrowables with the following data on [this contract](https://opbnbscan.com/address/0x73733C75EFcB7214c062C579EC8D0842Ae41eFa5). The function returns `undefined` .

user = 0xa445BC34f142808c5dCB0A68679159CC7Ac58329
assets = [0x2Cf0D30D00D88113dA4f0Ec04C7C336E5c3714B8]

Basically the code does a loop on `getUserMaxBorrowable`, which can take the same input except 1 asset only.

```solidity
  function getUserMaxBorrowables(address user, address[] memory assets) public view returns(uint256[] memory borrowables){
        if (assets.length > 0) {
            borrowables = new uint256[](assets.length);
            for (uint i;i < assets.length; i++) {
                borrowables[i] = getUserMaxBorrowable(user, assets[i]);
            }
        } 
  }
```

However after the return value in the function is initialised separately outside the returns spec in [this instance](https://opbnbscan.com/address/0xF6eeb49706179089Ef1Cdb1096b6d2fe03625379?tab=Contract&view=contract_code), it works:

```solidity
  function getUserMaxBorrowables(address user, address[] memory assets) public view returns(uint256[] memory){
    if (assets.length > 0) {
        uint256[] memory borrowables = new uint256[](assets.length);
            for (uint i;i < assets.length; i++) {
                borrowables[i] = getUserMaxBorrowable(user, assets[i]);
            }
        return borrowables;
        }      
    }
``` 

The 1st version of contract instance is working fine in BSC on our deployments, so I wonder what caused the discrepancy.

**Comment by CocoStarZ** [comment]
Which version did you use?

**Comment by owen-reorg** [comment]
Could you please provide an example of a function call, including the parameters needed to reproduce it?

**Comment by chrisckwong821** [comment]
sure, the issue includes the details and instances for reproduction:
function call:
`getUserMaxBorrowables`
user = 0xa445BC34f142808c5dCB0A68679159CC7Ac58329
assets = [0x2Cf0D30D00D88113dA4f0Ec04C7C336E5c3714B8]

Instance that does not work, return `undefined`
[this contract](https://opbnbscan.com/address/0x73733C75EFcB7214c062C579EC8D0842Ae41eFa5)

Instance that works
[this instance](https://opbnbscan.com/address/0xF6eeb49706179089Ef1Cdb1096b6d2fe03625379?tab=Contract&view=contract_code)

The difference between these two instances is described on above, where the returned data is specified in return type versus defined within the function.

The 1st instance works in BSC, that's why i wonder.

**Comment by owen-reorg** [comment]
The issue has been fixed.

<img width="911" alt="CleanShot 2023-09-05 at 12 08 37@2x" src="https://github.com/bnb-chain/opbnb/assets/103096885/87a3cd99-4dd5-4c55-81e4-87661f2e7cc0">
